// Generated by ilmarinen-convert from plugin/. Do not edit; run `just convert`.
// Runs the Ilmarinen Claude Code hook scripts from OpenCode. Exit 2 from a
// PreToolUse script blocks the tool (the plugin throws); any other non-zero
// exit is reported and ignored, as in Claude Code. See CONVERSION.md.
import type { Plugin } from "@opencode-ai/plugin"
import { fileURLToPath } from "node:url"

const HOOKS = fileURLToPath(new URL("../ilmarinen/hooks/", import.meta.url))
const TOOLS: Record<string, string> = {"bash":"Bash","edit":"Edit","glob":"Glob","grep":"Grep","read":"Read","write":"Write"}
type Rule = { event: string; tools: string[]; when: string | null; script: string; timeoutMs: number }
const RULES: Rule[] = [
  {
    "event": "PreToolUse",
    "tools": [
      "Bash",
      "Read",
      "Grep"
    ],
    "when": null,
    "script": "pre-tool-deny.sh",
    "timeoutMs": 10000
  },
  {
    "event": "PreToolUse",
    "tools": [
      "Bash"
    ],
    "when": "(^|[;&|(]\\s*)git\\s+commit(\\s|$)",
    "script": "leak-guard.sh",
    "timeoutMs": 30000
  },
  {
    "event": "PreToolUse",
    "tools": [
      "Bash"
    ],
    "when": null,
    "script": "hook-audit.sh",
    "timeoutMs": 10000
  },
  {
    "event": "SessionEnd",
    "tools": [],
    "when": null,
    "script": "session-end.sh",
    "timeoutMs": 600000
  },
  {
    "event": "Stop",
    "tools": [],
    "when": null,
    "script": "stop-check.sh",
    "timeoutMs": 600000
  }
]

function claudeInput(tool: string, args: any): Record<string, unknown> {
  switch (tool) {
    case "Bash": return { command: args?.command ?? "" }
    case "Read": case "Edit": case "Write": return { file_path: args?.filePath ?? "" }
    case "Grep": case "Glob": return { pattern: args?.pattern ?? "", path: args?.path ?? "" }
    default: return { ...(args ?? {}) }
  }
}

async function run(rule: Rule, payload: object, cwd: string) {
  const proc = Bun.spawn(["sh", HOOKS + rule.script], {
    cwd,
    stdin: new Blob([JSON.stringify(payload)]),
    stdout: "ignore",
    stderr: "pipe",
    timeout: rule.timeoutMs,
    env: { ...process.env, CLAUDE_PROJECT_DIR: cwd },
  })
  const [code, stderr] = await Promise.all([proc.exited, new Response(proc.stderr).text()])
  return { code, stderr: stderr.trim() }
}

function matching(event: string, tool: string, input: Record<string, unknown>) {
  return RULES.filter((r) => r.event === event && r.tools.includes(tool) &&
    (!r.when || new RegExp(r.when).test(String(input.command ?? ""))))
}

export const IlmarinenHooks: Plugin = async ({ directory }) => ({
  "tool.execute.before": async (input, output) => {
    const tool = TOOLS[input.tool]
    if (!tool) return
    const ti = claudeInput(tool, output.args)
    for (const r of matching("PreToolUse", tool, ti)) {
      const { code, stderr } = await run(r, { hook_event_name: "PreToolUse", tool_name: tool, tool_input: ti, cwd: directory }, directory)
      if (code === 2) throw new Error(stderr || `blocked by ${r.script}`)
      if (code !== 0) console.warn(`ilmarinen: ${r.script} exited ${code}: ${stderr}`)
    }
  },
  event: async ({ event }) => {
    if (event.type !== "session.idle") return
    for (const r of RULES.filter((r) => r.event === "SessionEnd" || r.event === "Stop")) {
      const { code, stderr } = await run(r, { hook_event_name: r.event, reason: "idle", stop_hook_active: false, cwd: directory }, directory)
      if (code !== 0) console.warn(`ilmarinen: ${r.script} exited ${code}: ${stderr}`)
    }
  },
  "tool.execute.after": async (input, output) => {
    const tool = TOOLS[input.tool]
    if (!tool) return
    const ti = claudeInput(tool, input.args)
    for (const r of matching("PostToolUse", tool, ti)) {
      const { code, stderr } = await run(r, { hook_event_name: "PostToolUse", tool_name: tool, tool_input: ti, cwd: directory }, directory)
      if (code === 2) output.output = `${output.output}\n\n${stderr}`
      else if (code !== 0) console.warn(`ilmarinen: ${r.script} exited ${code}: ${stderr}`)
    }
  },
})
