#!/bin/sh
# Source Reference check (SpecScore grammar, published detection regex).
# Fails on dangling references; warns on Requirements nothing verifies; writes
# artifacts/traceability.md. specscore:// references to other repos resolve
# against checkouts listed in ~/.config/ilmarinen/repos.toml.
set -eu
root=$(git rev-parse --show-toplevel); cd "$root"
repos=${ILMARINEN_CONFIG:-$HOME/.config/ilmarinen}/repos.toml
self=$(awk '/^project:/{p=1;next} /^[^ #]/{p=0} p&&$1=="host:"{h=$2} p&&$1=="org:"{o=$2} p&&$1=="repo:"{r=$2} END{print h"/"o"/"r}' specscore.yaml)
out=artifacts/traceability.md
tmp=$(mktemp -d); trap 'rm -rf "$tmp"' EXIT
RE='^[[:space:]]*(//|#|--|[/*]|%|;)[[:space:]]*(specscore:(implements|verifies|references)[[:space:]]+|specscore:|https://specscore\.org/)'

# 1. References: file:line <TAB> verb <TAB> target
git ls-files -co --exclude-standard -z | xargs -0 grep -IEnH "$RE" 2>/dev/null |
  grep -v -e '^spec/' -e '^artifacts/' -e '^scripts/trace\.sh:' |
  awk '{ split($0, a, ":"); loc=a[1]":"a[2]
         t=$0; sub(/^[^:]*:[0-9]+:/, "", t); verb="references"
         if (match(t, /specscore:(implements|verifies|references)[[:space:]]+/)) { v=substr(t,RSTART+10,RLENGTH-10); sub(/[[:space:]]+$/,"",v); verb=v; t=substr(t,RSTART+RLENGTH) }
         else if (match(t, /https:\/\/specscore\.org\//)) t=substr(t,RSTART)
         else if (match(t, /specscore:/)) { t=substr(t,RSTART+10)
           if (match(t, /^[a-z]+[[:space:]]+[^[:space:]]/)) { split(t, parts, /[[:space:]]+/); verb=parts[1]; t=parts[2] } }
         split(t, w, /[[:space:]]/); print loc "\t" verb "\t" w[1] }' > "$tmp/refs"

repo_path() { # host/org/repo -> checkout path
  [ "$1" = "$self" ] && { printf '%s' "$root"; return; }
  [ -f "$repos" ] && awk -v id="$1" '$1=="id"{gsub(/"/,"",$3); cur=$3} $1=="path"&&cur==id{gsub(/"/,"",$3); print $3; exit}' "$repos"
}
resolve() { # target -> "OK <file>" | "DANGLING <why>"
  t=$1; anchor=; case "$t" in *'#'*) anchor=${t#*#}; t=${t%%#*} ;; esac
  case "$t" in
    specscore://*) r=${t#specscore://}; id=$(printf '%s' "$r" | cut -d/ -f1-3); p=$(printf '%s' "$r" | cut -d/ -f4-) ;;
    https://specscore.org/*) r=${t#https://specscore.org/}; id=$(printf '%s' "$r" | cut -d/ -f1-3); p=$(printf '%s' "$r" | cut -d/ -f4-) ;;
    *) id=$self; p=$t ;;
  esac
  base=$(repo_path "$id"); [ -n "$base" ] || { echo "DANGLING repo $id not in repos.toml"; return; }
  case "$p" in feature/*) p=spec/features/${p#feature/} ;; plan/*) p=spec/plans/${p#plan/} ;; doc/*) p=docs/${p#doc/} ;; esac
  f=$base/$p; [ -d "$f" ] && f=$f/README.md
  [ -f "$f" ] || { echo "DANGLING no file $p in $id"; return; }
  case "$anchor" in
    req:*) grep -q "^#### REQ: ${anchor#req:}[[:space:]]*$" "$f" || { echo "DANGLING no REQ ${anchor#req:} in $p"; return; } ;;
    ac:*) grep -q "^### AC: ${anchor#ac:}\([[:space:]]\|$\)" "$f" || { echo "DANGLING no AC ${anchor#ac:} in $p"; return; } ;;
  esac
  echo "OK $f"
}

dangling=0
: > "$tmp/rows"
while IFS="$(printf '\t')" read -r loc verb target; do
  res=$(resolve "$target")
  case "$verb" in implements|verifies|references) ;; *) res="DANGLING unknown verb $verb" ;; esac
  case "$res" in DANGLING*) dangling=$((dangling + 1)); echo "trace: $loc: $verb $target: ${res#DANGLING }" >&2 ;; esac
  printf '| %s | %s | `%s` | %s |\n' "$loc" "$verb" "$target" "${res%% *}" >> "$tmp/rows"
done < "$tmp/refs"

# 2. Local Requirements with no verifying reference (directly or via an AC).
: > "$tmp/unverified"
find spec/features -mindepth 2 -name README.md 2>/dev/null | sort | while IFS= read -r f; do
  slug=${f#spec/features/}; slug=${slug%/README.md}
  sed -n 's/^#### REQ: \([^[:space:]]*\).*/\1/p' "$f" | while IFS= read -r req; do
    acs=$(sed -n "s/^### AC: \([^[:space:]]*\) (verifies REQ:$req).*/\1/p" "$f")
    hit=$(awk -F'\t' -v s="$slug" -v r="$req" -v acs=" $(echo $acs) " '$2=="verifies" { t=$3; sub(/^.*\/feature\//, "feature/", t); sub(/^.*\/spec\/features\//, "feature/", t)
          if (t=="feature/" s "#req:" r) { print; exit } n=split(acs, a, " "); for (i=1;i<=n;i++) if (t=="feature/" s "#ac:" a[i]) { print; exit } }' "$tmp/refs")
    [ -n "$hit" ] || { echo "trace: warning: feature/$slug#req:$req has no specscore:verifies" >&2; echo "- \`feature/$slug#req:$req\`" >> "$tmp/unverified"; }
  done
done

mkdir -p artifacts
{
  echo "# Traceability"; echo; echo "Generated by \`just trace\`; an Artifact, never committed."; echo
  echo "| Location | Verb | Target | Status |"; echo "|---|---|---|---|"; cat "$tmp/rows"; echo
  echo "## Requirements without a verifying reference"; echo
  if [ -s "$tmp/unverified" ]; then cat "$tmp/unverified"; else echo "None."; fi
} > "$out"
echo "trace: $(wc -l < "$tmp/refs" | tr -d ' ') reference(s), $dangling dangling; wrote $out"
[ "$dangling" -eq 0 ]
