//! `ilmarinen-convert`: emit `hosts/opencode/` from the Claude Code plugin in
//! `plugin/`. Pattern borrowed from EveryInc/compound-engineering-plugin
//! (decision 0007); no content borrowed. Anything OpenCode cannot express is
//! reported, never silently dropped.
//!
//! Output (an Artifact, `linguist-generated`):
//!   skills/<name>/…            copied verbatim
//!   ilmarinen/hooks/*.sh       copied verbatim (executable)
//!   plugins/ilmarinen.ts       one OpenCode plugin running the hook scripts
//!   opencode.json              the `mcp` block `setup` merges into the global config
//!   CONVERSION.md              what was mapped, rewritten, or could not be expressed

use crate::setup::to_opencode;
use anyhow::{Context, Result, bail};
use serde_json::{Value, json};
use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

pub const HEADER: &str = "Generated by ilmarinen-convert from plugin/. Do not edit; run `just convert`.";

/// Claude Code tool name → OpenCode tool id, for the tools our hooks match.
const TOOLS: &[(&str, &str)] =
    &[("Bash", "bash"), ("Read", "read"), ("Grep", "grep"), ("Glob", "glob"), ("Edit", "edit"), ("Write", "write")];

/// Claude Code events with an OpenCode plugin equivalent.
const EVENTS: &[(&str, &str)] = &[
    ("PreToolUse", "tool.execute.before"),
    ("PostToolUse", "tool.execute.after"),
    ("SessionEnd", "event session.idle"),
];

/// The accepted gap types: standing differences between the hosts, reported
/// on every run. Any other gap type fails the converter (and `just check`),
/// so neither a plugin change nor a host update widens the difference silently.
pub const ACCEPTED: &[(&str, &str)] = &[
    (
        "post-tool-use-advisory",
        "PostToolUse cannot block or re-prompt in OpenCode: `tool.execute.after` runs after the tool; on exit 2 the plugin appends the hook's stderr to the tool output so the agent still sees the failure. On OpenCode the post-edit check is advisory.",
    ),
    (
        "patch-tool-unhooked",
        "OpenCode's `patch` tool (multi-file edits) has no single file path, so Edit|Write hooks do not run for it.",
    ),
    (
        "if-as-regex",
        "`if` conditions are re-implemented as regexes over the Bash command; only `Bash(<prefix> *)` and `Bash(<exact>)` forms convert.",
    ),
    (
        "session-start-context",
        "SessionStart cannot inject context in OpenCode (`session.created` has no stdout channel), so the handoff note and `bd ready` are not shown automatically; OpenCode's user instructions tell the agent to run `bd recall ilmarinen-handoff` and `bd ready` at session start instead.",
    ),
    (
        "session-end-as-idle",
        "SessionEnd has no OpenCode equivalent; the handoff hook runs on `session.idle` (after every agent turn) instead, so the Beads note is refreshed each turn rather than once at exit.",
    ),
    (
        "json-output-ignored",
        "Hook JSON output (`permissionDecision`, `additionalContext`) is ignored; only exit code 2 blocks, as in Claude Code's exit-code protocol.",
    ),
];

/// Claude Code features this plugin does not use and OpenCode could not express.
pub const UNUSED: &str = "Not used by this plugin, and not expressible in OpenCode: SessionStart context injection, Stop/SubagentStop blocking, UserPromptSubmit blocking, PreCompact/PostCompact, Notification, SessionEnd, PermissionRequest, and `prompt`/`agent`/`http`/`mcp_tool` handler types.";

/// OpenCode plugin hooks the generated plugin relies on.
const HOST_HOOKS: &[&str] = &["\"tool.execute.before\"", "\"tool.execute.after\""];

#[derive(Default)]
pub struct Output {
    pub files: BTreeMap<PathBuf, (Vec<u8>, bool)>,
    pub report: Vec<String>,
    /// (gap type, description)
    pub gaps: Vec<(String, String)>,
}

impl Output {
    fn gap(&mut self, kind: &str, text: String) {
        self.gaps.push((kind.to_string(), text));
    }

    /// Gaps whose type is not in [`ACCEPTED`].
    pub fn unaccepted(&self) -> Vec<&(String, String)> {
        self.gaps.iter().filter(|(k, _)| !ACCEPTED.iter().any(|(a, _)| a == k)).collect()
    }

    fn add(&mut self, p: impl Into<PathBuf>, bytes: Vec<u8>, exec: bool) {
        self.files.insert(p.into(), (bytes, exec));
    }
}

pub fn convert(plugin: &Path) -> Result<Output> {
    let mut out = Output::default();
    skills(plugin, &mut out)?;
    mcp(plugin, &mut out)?;
    hooks(plugin, &mut out)?;
    for (k, t) in ACCEPTED {
        out.gap(k, t.to_string());
    }
    out.add("CONVERSION.md", conversion_md(&out).into_bytes(), false);
    Ok(out)
}

fn skill_name_ok(n: &str) -> bool {
    !n.is_empty()
        && n.len() <= 64
        && n.split('-').all(|p| !p.is_empty() && p.bytes().all(|b| b.is_ascii_lowercase() || b.is_ascii_digit()))
}

fn frontmatter_name(text: &str) -> Option<String> {
    let body = text.strip_prefix("---\n")?;
    let fm = &body[..body.find("\n---")?];
    fm.lines().find_map(|l| l.strip_prefix("name:").map(|v| v.trim().trim_matches('"').to_string()))
}

fn walk(dir: &Path, base: &Path, acc: &mut Vec<PathBuf>) -> Result<()> {
    let mut entries: Vec<_> = std::fs::read_dir(dir)?.flatten().map(|e| e.path()).collect();
    entries.sort();
    for p in entries {
        if p.is_dir() {
            walk(&p, base, acc)?;
        } else {
            acc.push(p.strip_prefix(base)?.to_path_buf());
        }
    }
    Ok(())
}

fn skills(plugin: &Path, out: &mut Output) -> Result<()> {
    let root = plugin.join("skills");
    let mut dirs: Vec<_> = std::fs::read_dir(&root)?.flatten().map(|e| e.path()).filter(|p| p.is_dir()).collect();
    dirs.sort();
    for d in dirs {
        let dir_name = d.file_name().unwrap().to_string_lossy().into_owned();
        let text = std::fs::read_to_string(d.join("SKILL.md")).with_context(|| format!("{}/SKILL.md", d.display()))?;
        let name =
            frontmatter_name(&text).with_context(|| format!("{dir_name}/SKILL.md has no `name:` frontmatter"))?;
        if name != dir_name || !skill_name_ok(&name) {
            bail!("skill {dir_name}: OpenCode needs name == directory and ^[a-z0-9]+(-[a-z0-9]+)*$ (got {name:?})");
        }
        if text.contains("~/.claude/") || text.contains("CLAUDE_PLUGIN_ROOT") {
            out.gap("claude-only-path", format!("skill `{name}` references a Claude-only path; copied unchanged"));
        }
        let mut files = Vec::new();
        walk(&d, &d, &mut files)?;
        for f in files {
            out.add(Path::new("skills").join(&dir_name).join(&f), std::fs::read(d.join(&f))?, false);
        }
        out.report.push(format!("skill    {name}"));
    }
    Ok(())
}

/// Host-specific argument rewrites for OpenCode (reported).
fn rewrite_args(name: &str, spec: &mut Value, out: &mut Output) {
    if name != "serena" {
        return;
    }
    if let Some(args) = spec.get_mut("args").and_then(Value::as_array_mut) {
        for i in 1..args.len() {
            if args[i - 1] == "--context" && args[i] == "claude-code" {
                args[i] = json!("ide");
                out.report.push("mcp      serena: --context claude-code → ide (Serena's context for hosts with their own file tools)".into());
            }
        }
    }
}

fn mcp(plugin: &Path, out: &mut Output) -> Result<()> {
    let v: Value = serde_json::from_str(&std::fs::read_to_string(plugin.join(".mcp.json"))?)?;
    let servers = v.get("mcpServers").and_then(Value::as_object).context(".mcp.json has no mcpServers")?;
    let mut mcp = serde_json::Map::new();
    for (name, spec) in servers {
        let mut spec = spec.clone();
        rewrite_args(name, &mut spec, out);
        mcp.insert(name.clone(), to_opencode(&spec)?);
        out.report.push(format!("mcp      {name}"));
    }
    let doc = json!({"$schema": "https://opencode.ai/config.json", "mcp": mcp});
    out.add("opencode.json", (serde_json::to_string_pretty(&doc)? + "\n").into_bytes(), false);
    Ok(())
}

/// `Bash(git commit *)` → a JS regex source matching that command anywhere in
/// a compound command line.
pub fn if_to_regex(cond: &str) -> Option<String> {
    let inner = cond.strip_prefix("Bash(")?.strip_suffix(')')?;
    let (words, open) = match inner.strip_suffix(" *") {
        Some(w) => (w, true),
        None => (inner, false),
    };
    if words.is_empty() || words.contains(['*', '?', '(', ')']) {
        return None;
    }
    let body: Vec<String> = words.split_whitespace().map(regex::escape).collect();
    let tail = if open { r"(\s|$)" } else { r"\s*($|[;&|])" };
    Some(format!(r"(^|[;&|(]\s*){}{tail}", body.join(r"\s+")))
}

fn script_of(cmd: &str) -> Option<String> {
    let c = cmd.trim().trim_matches('"');
    let s = c.strip_prefix("${CLAUDE_PLUGIN_ROOT}/hooks/")?;
    (!s.contains(['/', ' ', '"'])).then(|| s.to_string())
}

fn hooks(plugin: &Path, out: &mut Output) -> Result<()> {
    let dir = plugin.join("hooks");
    let v: Value = serde_json::from_str(&std::fs::read_to_string(dir.join("hooks.json"))?)?;
    let events = v.get("hooks").and_then(Value::as_object).context("hooks.json has no `hooks`")?;
    let mut rules = Vec::new();
    for (event, groups) in events {
        if event == "SessionStart" {
            continue; // accepted gap `session-start-context`, always reported
        }
        let Some((_, oc_event)) = EVENTS.iter().find(|(e, _)| e == event) else {
            out.gap(
                "unsupported-event",
                format!("event `{event}` has no OpenCode equivalent; its hooks are not converted"),
            );
            continue;
        };
        for g in groups.as_array().into_iter().flatten() {
            let matcher = g.get("matcher").and_then(Value::as_str).unwrap_or("*");
            let mut tools = Vec::new();
            let session = event.starts_with("Session");
            for t in matcher.split(['|', ',']).map(str::trim).filter(|_| !session) {
                match TOOLS.iter().find(|(c, _)| *c == t) {
                    Some((c, _)) => tools.push(*c),
                    None => out.gap(
                        "unmapped-matcher",
                        format!("{event} matcher `{t}` has no OpenCode tool; skipped for that tool"),
                    ),
                }
            }
            for h in g.get("hooks").and_then(Value::as_array).into_iter().flatten() {
                let cmd = h.get("command").and_then(Value::as_str).unwrap_or_default();
                let kind = h.get("type").and_then(Value::as_str).unwrap_or("command");
                let Some(script) = (kind == "command").then(|| script_of(cmd)).flatten() else {
                    out.gap(
                        "unsupported-handler",
                        format!("{event} handler `{kind}: {cmd}` is not a plugin hook script; not converted"),
                    );
                    continue;
                };
                let when = match h.get("if").and_then(Value::as_str) {
                    None => None,
                    Some(c) => match if_to_regex(c) {
                        Some(re) => Some(re),
                        None => {
                            out.gap(
                                "unconvertible-if",
                                format!("{event} `{script}`: `if: {c}` cannot be expressed; hook not converted"),
                            );
                            continue;
                        }
                    },
                };
                let timeout = h.get("timeout").and_then(Value::as_u64).unwrap_or(600);
                out.report.push(format!(
                    "hook     {event} → {oc_event}: {script} on {}{}",
                    tools.join("|"),
                    h.get("if").and_then(Value::as_str).map(|c| format!(" if {c}")).unwrap_or_default()
                ));
                rules.push(json!({"event": event, "tools": tools, "when": when, "script": script, "timeoutMs": timeout * 1000}));
            }
        }
    }
    let mut scripts: Vec<_> = std::fs::read_dir(&dir)?
        .flatten()
        .map(|e| e.path())
        .filter(|p| p.extension().is_some_and(|e| e == "sh"))
        .collect();
    scripts.sort();
    for s in scripts {
        out.add(Path::new("ilmarinen/hooks").join(s.file_name().unwrap()), std::fs::read(&s)?, true);
    }
    let tools_js: BTreeMap<&str, &str> = TOOLS.iter().map(|(c, o)| (*o, *c)).collect();
    let ts = PLUGIN_TS
        .replace("__HEADER__", HEADER)
        .replace("__TOOLS__", &serde_json::to_string(&tools_js)?)
        .replace("__RULES__", &serde_json::to_string_pretty(&rules)?);
    out.add("plugins/ilmarinen.ts", ts.into_bytes(), false);
    Ok(())
}

fn conversion_md(out: &Output) -> String {
    let mut s = format!("# OpenCode conversion report\n\n{HEADER}\n\n## Converted\n\n");
    for r in &out.report {
        s.push_str(&format!("- `{}`\n", r.trim()));
    }
    s.push_str("\n## Gaps (OpenCode cannot express)\n\nOnly the types below are accepted; any other type fails `ilmarinen-convert` and `just check`.\n\n");
    for (k, t) in &out.gaps {
        s.push_str(&format!("- `{k}`: {t}\n"));
    }
    s.push_str(&format!("\n{UNUSED}\n"));
    s
}

/// Probe installed OpenCode plugin typings (if any) for the hooks the
/// generated plugin uses. Kept out of CONVERSION.md, which must not depend on
/// the machine. Returns a note for the output; adds a gap if a hook vanished.
pub fn probe_host(out: &mut Output, typings: &[PathBuf]) -> String {
    let Some((path, text)) = typings.iter().find_map(|p| std::fs::read_to_string(p).ok().map(|t| (p, t))) else {
        return "OpenCode plugin typings not found; host hooks not probed".into();
    };
    for h in HOST_HOOKS {
        if !text.contains(h) {
            out.gap(
                "host-hook-missing",
                format!("installed OpenCode typings ({}) no longer declare {h}", path.display()),
            );
        }
    }
    format!("probed OpenCode hooks in {}", path.display())
}

/// Write `out` to `dir`, deleting files there that are no longer generated.
/// With `check`, write nothing and return whether `dir` is already current.
pub fn sync(out: &Output, dir: &Path, check: bool) -> Result<bool> {
    let mut existing = Vec::new();
    if dir.is_dir() {
        walk(dir, dir, &mut existing)?;
    }
    let mut current = true;
    for (p, (bytes, exec)) in &out.files {
        let target = dir.join(p);
        if std::fs::read(&target).ok().as_deref() != Some(bytes.as_slice()) {
            current = false;
            if !check {
                crate::util::write(&target, bytes)?;
            }
        }
        #[cfg(unix)]
        if *exec && !check {
            use std::os::unix::fs::PermissionsExt;
            std::fs::set_permissions(&target, std::fs::Permissions::from_mode(0o755))?;
        }
    }
    for p in existing.iter().filter(|p| !out.files.contains_key(*p)) {
        current = false;
        if !check {
            std::fs::remove_file(dir.join(p))?;
        }
    }
    Ok(current)
}

const PLUGIN_TS: &str = r#"// __HEADER__
// Runs the Ilmarinen Claude Code hook scripts from OpenCode. Exit 2 from a
// PreToolUse script blocks the tool (the plugin throws); any other non-zero
// exit is reported and ignored, as in Claude Code. See CONVERSION.md.
import type { Plugin } from "@opencode-ai/plugin"
import { fileURLToPath } from "node:url"

const HOOKS = fileURLToPath(new URL("../ilmarinen/hooks/", import.meta.url))
const TOOLS: Record<string, string> = __TOOLS__
type Rule = { event: string; tools: string[]; when: string | null; script: string; timeoutMs: number }
const RULES: Rule[] = __RULES__

function claudeInput(tool: string, args: any): Record<string, unknown> {
  switch (tool) {
    case "Bash": return { command: args?.command ?? "" }
    case "Read": case "Edit": case "Write": return { file_path: args?.filePath ?? "" }
    case "Grep": case "Glob": return { pattern: args?.pattern ?? "", path: args?.path ?? "" }
    default: return { ...(args ?? {}) }
  }
}

async function run(rule: Rule, payload: object, cwd: string) {
  const proc = Bun.spawn(["sh", HOOKS + rule.script], {
    cwd,
    stdin: new Blob([JSON.stringify(payload)]),
    stdout: "ignore",
    stderr: "pipe",
    timeout: rule.timeoutMs,
    env: { ...process.env, CLAUDE_PROJECT_DIR: cwd },
  })
  const [code, stderr] = await Promise.all([proc.exited, new Response(proc.stderr).text()])
  return { code, stderr: stderr.trim() }
}

function matching(event: string, tool: string, input: Record<string, unknown>) {
  return RULES.filter((r) => r.event === event && r.tools.includes(tool) &&
    (!r.when || new RegExp(r.when).test(String(input.command ?? ""))))
}

export const IlmarinenHooks: Plugin = async ({ directory }) => ({
  "tool.execute.before": async (input, output) => {
    const tool = TOOLS[input.tool]
    if (!tool) return
    const ti = claudeInput(tool, output.args)
    for (const r of matching("PreToolUse", tool, ti)) {
      const { code, stderr } = await run(r, { hook_event_name: "PreToolUse", tool_name: tool, tool_input: ti, cwd: directory }, directory)
      if (code === 2) throw new Error(stderr || `blocked by ${r.script}`)
      if (code !== 0) console.warn(`ilmarinen: ${r.script} exited ${code}: ${stderr}`)
    }
  },
  event: async ({ event }) => {
    if (event.type !== "session.idle") return
    for (const r of RULES.filter((r) => r.event === "SessionEnd")) {
      const { code, stderr } = await run(r, { hook_event_name: "SessionEnd", reason: "idle", cwd: directory }, directory)
      if (code !== 0) console.warn(`ilmarinen: ${r.script} exited ${code}: ${stderr}`)
    }
  },
  "tool.execute.after": async (input, output) => {
    const tool = TOOLS[input.tool]
    if (!tool) return
    const ti = claudeInput(tool, input.args)
    for (const r of matching("PostToolUse", tool, ti)) {
      const { code, stderr } = await run(r, { hook_event_name: "PostToolUse", tool_name: tool, tool_input: ti, cwd: directory }, directory)
      if (code === 2) output.output = `${output.output}\n\n${stderr}`
      else if (code !== 0) console.warn(`ilmarinen: ${r.script} exited ${code}: ${stderr}`)
    }
  },
})
"#;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn if_conditions() {
        let re = regex::Regex::new(&if_to_regex("Bash(git commit *)").unwrap()).unwrap();
        assert!(re.is_match("git commit -m x"));
        assert!(re.is_match("git add . && git  commit"));
        assert!(!re.is_match("git commitx"));
        assert!(!re.is_match("echo git log"));
        let exact = regex::Regex::new(&if_to_regex("Bash(npm test)").unwrap()).unwrap();
        assert!(exact.is_match("npm test") && !exact.is_match("npm test --watch"));
        assert!(if_to_regex("Read(./.env)").is_none());
        assert!(if_to_regex("Bash(rm -rf /*)").is_none());
    }

    #[test]
    fn only_accepted_gaps_for_repo_plugin_and_probe() {
        let plugin = Path::new(concat!(env!("CARGO_MANIFEST_DIR"), "/../plugin"));
        let mut out = convert(plugin).unwrap();
        assert!(out.unaccepted().is_empty(), "{:?}", out.unaccepted());
        assert_eq!(out.gaps.len(), ACCEPTED.len());
        let ts = String::from_utf8(out.files[&PathBuf::from("plugins/ilmarinen.ts")].0.clone()).unwrap();
        assert!(ts.contains("session-end.sh") && ts.contains("session.idle") && !ts.contains("session-start.sh"));
        let t = tempfile::TempDir::new().unwrap();
        let d = t.path().join("index.d.ts");
        std::fs::write(&d, "\"tool.execute.before\"?: x").unwrap();
        probe_host(&mut out, &[d]);
        let bad: Vec<_> = out.unaccepted().iter().map(|(k, _)| k.clone()).collect();
        assert_eq!(bad, ["host-hook-missing"]);
    }

    #[test]
    fn skill_names() {
        assert!(skill_name_ok("route") && skill_name_ok("a-b1"));
        assert!(!skill_name_ok("Route") && !skill_name_ok("a--b") && !skill_name_ok("-a"));
        assert_eq!(frontmatter_name("---\nname: plan\ndescription: x\n---\nbody"), Some("plan".into()));
    }

    #[test]
    fn converts_repo_plugin() {
        let plugin = Path::new(concat!(env!("CARGO_MANIFEST_DIR"), "/../plugin"));
        let out = convert(plugin).unwrap();
        for s in ["route", "blueprint", "rune", "plan", "forge", "verify", "sampo", "survey"] {
            assert!(out.files.contains_key(&PathBuf::from(format!("skills/{s}/SKILL.md"))), "{s}");
        }
        let oc: Value = serde_json::from_slice(&out.files[&PathBuf::from("opencode.json")].0).unwrap();
        assert_eq!(oc["mcp"].as_object().unwrap().len(), 5);
        assert!(oc["mcp"]["serena"]["command"].as_array().unwrap().contains(&json!("ide")));
        let ts = String::from_utf8(out.files[&PathBuf::from("plugins/ilmarinen.ts")].0.clone()).unwrap();
        assert!(ts.contains("pre-tool-deny.sh") && ts.contains("leak-guard.sh") && ts.contains("post-edit-check.sh"));
        assert!(out.files[&PathBuf::from("ilmarinen/hooks/pre-tool-deny.sh")].1, "scripts are executable");
    }
}
